accounts/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register(r'customers', views.CustomerViewSet)
router.register(r'stocks', views.StockViewSet)
router.register(r'cryptocurrency', views.CryptocurrencyViewSet)

urlpatterns =[
    url(r'^$', views.index, name='index'),
    url(r'^customer/new/$', views.customer_new, name='customer_new'),
    url(r'^stock/new/$', views.stock_new, name='stock_new'),
    url(r'^crypto/new/$', views.crypto_new, name='crypto_new'),
    url(r'^(?P<customer_id>[0-9]+)/$', views.customer_detail, name='customer'),
    url(r'^(?P<customer_id>[0-9]+)/edit/$', views.customer_edit, name='customer_edit'),
    url(r'^(?P<customer_id>[0-9]+)/delete$', views.customer_delete, name='customer_delete'),
    url(r'^[0-9]+/stock/(?P<stock_id>[0-9]+)/$', views.stock_detail, name='stock'),
    url(r'^[0-9]+/stock/(?P<stock_id>[0-9]+)/edit/$', views.stock_edit, name='stock_edit'),
    url(r'^[0-9]+/stock/(?P<stock_id>[0-9]+)/delete/$', views.stock_delete, name='stock_delete'),
    url(r'^[0-9]+/crypto/(?P<crypto_id>[0-9]+)/$', views.crypto_detail, name='crypto'),
    url(r'^[0-9]+/crypto/(?P<crypto_id>[0-9]+)/edit/$', views.crypto_edit, name='crypto_edit'),
    url(r'^[0-9]+/crypto/(?P<crypto_id>[0-9]+)/delete/$', views.crypto_delete, name='crypto_delete'),
    url(r'^api/', include(router.urls)),
]

untitled/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', include('accounts.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.utils import timezone


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    street = models.TextField()
    city = models.TextField()
    state = models.CharField(max_length=2)
    zip = models.CharField(max_length=5)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

class Stock(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    symbol = models.CharField(max_length=30)
    name = models.TextField()
    number_of_shares = models.FloatField()
    purchase_price = models.FloatField()
    date_purchased = models.DateTimeField(blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{}: {}".format(self.customer.name, self.symbol)

class Cryptocurrency(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    symbol = models.CharField(max_length=30)
    name = models.TextField()
    number_of_coins = models.FloatField()
    purchase_price = models.FloatField()
    date_purchased = models.DateTimeField(blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{}: {}".format(self.customer.name, self.symbol)

accounts/forms.py
from django import forms

from .models import Customer
from .models import Stock
from .models import Cryptocurrency

class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = ('name', 'street', 'city', 'state', 'zip', 'email', 'phone')

class StockForm(forms.ModelForm):

    class Meta:
        model = Stock
        fields = ('customer','symbol', 'name', 'number_of_shares', 'purchase_price', 'date_purchased')

class CryptocurrencyForm(forms.ModelForm):

    class Meta:
        model = Cryptocurrency
        fields = ('customer', 'symbol', 'name', 'number_of_coins', 'purchase_price', 'date_purchased')

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Customer, Stock, Cryptocurrency
from rest_framework import viewsets
from .serializers import CustomerSerializer, StockSerializer, CryptoSerializer
from .services import get_stock_price, get_crypto_price
from .forms import CryptocurrencyForm, CustomerForm, StockForm
from django.shortcuts import redirect
from django.utils import timezone

def index(request):
    customer_list = Customer.objects.all()
    context = {'customer_list': customer_list}
    return render(request, 'accounts/index.html', context)

def customer_detail(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    context = {'customer': customer}
    return render(request, 'accounts/customer_detail.html', context)

def stock_detail(request, stock_id):
    stock = get_object_or_404(Stock, pk=stock_id)
    stock.current_price = get_stock_price(stock.symbol)
    stock.original_value = stock.purchase_price * stock.number_of_shares
    stock.current_value = stock.current_price * stock.number_of_shares
    stock.profit = stock.current_value - stock.original_value
    context = {'stock': stock}
    return render(request, 'accounts/stock_detail.html', context)

def crypto_detail(request, crypto_id):
    crypto = get_object_or_404(Cryptocurrency, pk=crypto_id)
    crypto.current_price = get_crypto_price(crypto.symbol)
    crypto.original_value = crypto.purchase_price * crypto.number_of_coins
    crypto.current_value = crypto.current_price * crypto.number_of_coins
    crypto.profit = crypto.current_value - crypto.original_value
    context = {'crypto': crypto}
    return render(request, 'accounts/crypto_detail.html', context)

def crypto_edit(request, crypto_id):
    crypto = get_object_or_404(Cryptocurrency, pk = crypto_id)
    if request.method =="POST":
        form = CryptocurrencyForm(request.POST, instance=crypto)
        if form.is_valid():
            crypto = form.save(commit=False)
            crypto.modified = timezone.now()
            crypto.save()
            return redirect('crypto', crypto_id=crypto_id)
    else:
        form = CryptocurrencyForm(instance=crypto)
    return render(request, 'accounts/crypto_edit.html', {'form': form})

def stock_edit(request, stock_id):
    stock = get_object_or_404(Stock, pk = stock_id)
    if request.method =="POST":
        form = StockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.modified = timezone.now()
            stock.save()
            return redirect('stock', stock_id=stock_id)
    else:
        form = StockForm(instance=stock)
    return render(request, 'accounts/stock_edit.html', {'form': form})

def customer_edit(request, customer_id):
    customer = get_object_or_404(Customer, pk = customer_id)
    if request.method =="POST":
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.modified = timezone.now()
            customer.save()
            return redirect('customer', customer_id=customer_id)
    else:
        form = CustomerForm(instance=customer)
    return render(request, 'accounts/customer_edit.html', {'form': form})

def customer_delete(request, customer_id):
    instance = Customer.objects.get(id=customer_id)
    instance.delete()
    return redirect('index')

def stock_delete(request, stock_id):
    instance = Stock.objects.get(id=stock_id)
    instance.delete()
    return redirect('customer', customer_id=instance.customer.id)

def crypto_delete(request, crypto_id):
    instance = Cryptocurrency.objects.get(id=crypto_id)
    instance.delete()
    return redirect('customer', customer_id=instance.customer.id)

def customer_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.created = timezone.now()
            customer.save()
            return redirect('customer', customer_id=customer.pk)
    else:
        form = CustomerForm()
    return render(request, 'accounts/customer_edit.html', {'form': form})

def stock_new(request):
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.created = timezone.now()
            stock.date_purchased = timezone.now()
            stock.save()
            return redirect('stock', stock_id=stock.pk)
    else:
        form = StockForm()
    return render(request, 'accounts/stock_edit.html', {'form': form})

def crypto_new(request):
    if request.method == "POST":
        form = CryptocurrencyForm(request.POST)
        if form.is_valid():
            crypto = form.save(commit=False)
            crypto.created = timezone.now()
            crypto.date_purchased = timezone.now()
            crypto.save()
            return redirect('crypto', crypto_id=crypto.pk)
    else:
        form = CryptocurrencyForm()
    return render(request, 'accounts/stock_edit.html', {'form': form})

class CustomerViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer


class StockViewSet(viewsets.ModelViewSet):
    queryset = Stock.objects.all()
    serializer_class = StockSerializer

class CryptocurrencyViewSet(viewsets.ModelViewSet):
    queryset = Cryptocurrency.objects.all()
    serializer_class = CryptoSerializer

templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>
  <body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
<head>
    <meta charset="UTF-8">
    <title>Financial Application</title>
</head>
<body>
    <div class="jumbotron">
        <h1>Financial Application</h1>
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

templates/accounts/crypto_detail.html
{% extends 'accounts/base.html' %}

{% block content %}
    {% if crypto %}
        <h2>{{ crypto.symbol }}({{ crypto.customer.name }})</h2>
        <h2>{{ crypto.name }}</h2>
        <table class= 'table table-striped'>
            <tr>
                <th>Purchase Price</th>
                <th>Number of Coins</th>
                <th>Current Price</th>
                <th>Current Value</th>
                <th>Current Profit</th>
            </tr>
            <tr>
                <td>{{ crypto.purchase_price }}</td>
                <td>{{ crypto.number_of_coins }}</td>
                <td>{{ crypto.current_price }}</td>
                <td>{{ crypto.current_value|floatformat:2 }}</td>
                <td>{{ crypto.profit|floatformat:2 }}</td>
            </tr>
        </table>
        <button type="button" class="btn btn-outline-primary"><a href="{% url 'customer' crypto.customer.id %}">Return</a></button>
        <button type="button" class="btn btn-outline-warning"><a href="{% url 'crypto_edit' crypto.id %}">Edit</a></button>
        <button type="button" class="btn btn-outline-danger"><a href="{% url 'crypto_delete'  crypto.id %}">Delete</a></button>
    {% else %}
        <p>No cryptocurrency found.</p>
    {% endif %}
{% endblock %}

templates/accounts/crypto_edit.html
{% extends 'accounts/base.html' %}

{% block content %}
    <html>
        <head>
            <title>Cryptocurrency Info</title>
        </head>
        <body>
             <h1>Cryptocurrency Info</h1>
             <form method="POST" class="cryptocurrency-form">{% csrf_token %}
                 {{ form.as_p }}
                 <p>
                    Enter date as: "YYYY-MM-DD HH:MM:SS" using military time, or leave blank to enter the current time.
                 </p>
                 <button type="submit" class="btn btn-outline-success">Save</button>
             </form>
        </body>
    </html>
{% endblock %}

templates/accounts/customer_detail.html
{% extends 'accounts/base.html' %}

{% block content %}
{% if customer %}
    <h1>{{ customer.name }}</h1>
    <p><a href="mailto:{{ customer.email }}">{{ customer.email }}</a></p>
    <p>{{ customer.phone }}</p>
    <p>{{ customer.street }} {{ customer.city }}, {{ customer.state }} {{ customer.zip }}</p>
    <button type="button" class="btn btn-outline-primary"><a href="{% url 'index'  %}">Return</a></button>
     <button type="button" class="btn btn-outline-warning"><a href="{% url 'customer_edit' customer.id %}">Edit</a></button>
    <button type="button" class="btn btn-outline-danger"><a href="{% url 'customer_delete'  customer.id %}">Delete</a></button>
    <ul>
        <h1>Stocks</h1>
            <table class= 'table table-striped'>
                <tr>
                    <th>Stock Symbol</th>
                    <th>Number of Shares Purchased</th>
                </tr>
                {% for stock in customer.stock_set.all %}
                <tr>
                    <td><a href="{% url 'stock' stock.id %}">{{ stock.symbol }}</a></td>
                    <td>{{ stock.number_of_shares }}</td><br>
                    <td>{{ crypto.number_of_coins_purchased }}</td><br>
                </tr>
                {% endfor %}
            </table>
    </ul>
    <button type="button" class="btn btn-outline-primary"><a href="{% url 'stock_new' %}">Add Stock</a></button>
    <ul>
        <h1>Cryptocurrencies</h1>
            <table class= 'table table-striped'>
                <tr>
                    <th>Crypto Symbol</th>
                    <th>Number of Coins Purchased</th>
                </tr>
                {% for crypto in customer.cryptocurrency_set.all %}
                <tr>
                    <td><a href="{% url 'crypto' crypto.id %}">{{ crypto.symbol }}</a></td>
                    <td>{{ crypto.number_of_coins }}</td>
                </tr><br>
                {% endfor %}
            </table>
    </ul>
        <button type="button" class="btn btn-outline-primary"><a href="{% url 'crypto_new' %}">Add Coin</a></button>
    {% else %}
    <p>No customer found.</p>

    {% endif %}
{% endblock %}

templates/accounts/customer_edit.html
{% extends 'accounts/base.html' %}

{% block content %}
    <html>
    <head>
        <title>Customer Info</title>
    </head>
    <body>
         <h1>Customer Info</h1>
         <form method="POST" class="customer-form">{% csrf_token %}
             {{ form.as_p }}
             <button type="submit" class="btn btn-outline-success">Save</button>
         </form>
    </body>
    </html>
{% endblock %}

templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block content %}
    {% if customer_list %}

        <ul>
            {% for customer in customer_list %}
                <li><a href="/accounts/{{ customer.id }}/">{{  customer.name }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <p>No customer information available.</p>
    {% endif %}
    <button type="button" class="btn btn-outline-primary"><a href="{% url 'customer_new' %}">Add Customer</a></button>
{% endblock %}

templates/accounts/stock_detail.html
{% extends 'accounts/base.html' %}

{% block content %}
    {% if stock %}
        <h1>{{ stock.symbol }}({{ stock.customer.name }})</h1>
        <table class= 'table table-striped'>
            <tr>
                <th>Purchase Price</th>
                <th>Number of Shares</th>
                <th>Current Price</th>
                <th>Current Value</th>
                <th>Current Profit</th>
            </tr>
            <tr>
                <td>{{ stock.purchase_price }}</td>
                <td>{{ stock.number_of_shares }}</td>
                <td>{{ stock.current_price }}</td>
                <td>{{ stock.current_value|floatformat:2 }}</td>
                <td>{{ stock.profit|floatformat:2 }}</td>
            </tr>
        </table>
        <button type="button" class="btn btn-outline-primary"><a href="{% url 'customer' stock.customer.id %}">Return</a></button>
        <button type="button" class="btn btn-outline-warning"><a href="{% url 'stock_edit' stock.id %}">Edit</a></button>
        <button type="button" class="btn btn-outline-danger"><a href="{% url 'stock_delete'  stock.id %}">Delete</a></button>
    {% else %}
        <p>No stock found.</p>
    {% endif %}
{% endblock %}

templates/accounts/stock_edit.html
{% extends 'accounts/base.html' %}

{% block content %}
    <html>
        <head>
            <title>Stock Info</title>
        </head>
        <body>
             <h1>Stock Info</h1>
             <form method="POST" class="stock-form">{% csrf_token %}
                 {{ form.as_p }}
                 <p>
                    Enter date as: "YYYY-MM-DD HH:MM:SS" using military time, or leave blank to enter the current time
                 </p>
                 <button type="success" class="btn btn-outline-success">Save</button>
             </form>
        </body>
    </html>
{% endblock %}